tools:
  jdk: 9
  maven: 3.5.3
 
flows:
  default:
    - call: init
    - call: versions
    - call: build
    - call: notify

  init:
    - shell: echo "Hello spring! tttt"

  versions:
    - shell(name JDK version): java -version
    - (name Maven version) mvn -v
    - shell(name Python check): python --version

  build:
    - echo "build TBD"

  notify:
    - echo "notify tbd"

